name: picfeed
description: App to read pictures from user feeds on reddit and pixiv.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reddit: any

flutter:
  uses-material-design: true
